# Códigos de mensaje para respuestas de la API

# Éxito
SUCCESS = "SUCCESS"
USER_REGISTERED = "USER_REGISTERED"
LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL"
QR_GENERATED = "QR_GENERATED"
PAYMENT_SUCCESSFUL = "PAYMENT_SUCCESSFUL"
TOPUP_SUCCESSFUL = "TOPUP_SUCCESSFUL"
PAYMENT_METHOD_ADDED = "PAYMENT_METHOD_ADDED"
PAYMENT_METHOD_REMOVED = "PAYMENT_METHOD_REMOVED"
PASSWORD_UPDATED = "PASSWORD_UPDATED"

# Éxito - Choferes
DRIVER_REGISTERED = "DRIVER_REGISTERED"
DRIVER_LOGIN_SUCCESSFUL = "DRIVER_LOGIN_SUCCESSFUL"
ROUTE_CREATED = "ROUTE_CREATED"
ROUTE_UPDATED = "ROUTE_UPDATED"
ROUTE_DELETED = "ROUTE_DELETED"
DRIVER_ROUTE_ASSIGNED = "DRIVER_ROUTE_ASSIGNED"
PAYMENT_PROCESSED_BY_DRIVER = "PAYMENT_PROCESSED_BY_DRIVER"

# Errores de autenticación
INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
UNAUTHORIZED = "UNAUTHORIZED"
INVALID_TOKEN = "INVALID_TOKEN"
TOKEN_EXPIRED = "TOKEN_EXPIRED"

# Errores de validación
VALIDATION_ERROR = "VALIDATION_ERROR"
INVALID_EMAIL = "INVALID_EMAIL"
WEAK_PASSWORD = "WEAK_PASSWORD"
INVALID_CARD = "INVALID_CARD"
INVALID_CARD_DETAILS = "INVALID_CARD_DETAILS"
INVALID_QR_CODE = "INVALID_QR_CODE"

# Errores de negocio
USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
USER_NOT_FOUND = "USER_NOT_FOUND"
INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE"
PAYMENT_METHOD_NOT_FOUND = "PAYMENT_METHOD_NOT_FOUND"
PAYMENT_FAILED = "PAYMENT_FAILED"

# Errores de negocio - Choferes
DRIVER_ALREADY_EXISTS = "DRIVER_ALREADY_EXISTS"
DRIVER_NOT_FOUND = "DRIVER_NOT_FOUND"
ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND"
ROUTE_ALREADY_EXISTS = "ROUTE_ALREADY_EXISTS"
DRIVER_NOT_ASSIGNED_TO_ROUTE = "DRIVER_NOT_ASSIGNED_TO_ROUTE"
INVALID_ROUTE_DATA = "INVALID_ROUTE_DATA"

# Errores del servidor
INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
